name: Run Dockerized App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
permissions:
  contents: write 
jobs:

  run-docker-app:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: |
        docker build -t data-automation-image .

    - name: Run Docker container and stream logs
      run: |
        # Run container in detached mode
        docker run -d --name data-automation-container data-automation-image

        echo "Container started. Tailing logs..."
        # Tail logs to get them printed in GitHub Actions
        docker logs -f data-automation-container

    - name: Set up tmate session
      uses: mxschmitt/action-tmate@v3
    #- name: Cleanup Docker container
    #  if: always()
    #  run: |
    #    docker stop data-automation-container
    #    docker rm data-automation-containers
